---
# Build OCI image and push to Forgejo Container Registry.
name: Build OCI container

on:
  push:
    branches:
      - "main"

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-push:
    name: Build and push image
    runs-on: opensuse-base-16.0-v1
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REGISTRY: ""
      REGISTRY_PROVIDER: dev.a8n.run
      REGISTRY_USER: ""
      REGISTRY_PASSWORD: ${{ secrets.FORGEJO_PAT }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      # The repository owner needs to be lowercase.
      - name: Set environment variables
        shell: nu {0}
        run: |
          let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
          $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
          $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV

      - name: Build image
        id: build-image
        shell: nu {0}
        run: |
          cd oci-build
          ./build.nu

      - name: Push image to Forgejo Container Registry
        id: push-to-forgejo
        shell: nu {0}
        run: |
          # Login to the registry
          let password_masked = ($env.REGISTRY_PASSWORD | str substring 0..3) + "***"
          print $"DEBUG: docker login --username ($env.REGISTRY_USER) --password ($password_masked) ($env.REGISTRY_PROVIDER)"
          ^docker login --username $env.REGISTRY_USER --password $env.REGISTRY_PASSWORD $env.REGISTRY_PROVIDER

          let image = "${{ steps.build-image.outputs.image }}"
          let tag = "${{ steps.build-image.outputs.tags }}"
          let registry = $env.IMAGE_REGISTRY
          let dest = $"($registry)/($image):($tag)"

          # Tag and push
          print $"DEBUG: docker tag ($image):($tag) ($dest)"
          ^docker tag $"($image):($tag)" $dest

          print $"DEBUG: docker push ($dest)"
          ^docker push $dest

          $"registry-paths=($dest)\n" | save --append $env.GITHUB_OUTPUT

      - name: Print image URL
        run: echo "Production image pushed to ${{ steps.push-to-forgejo.outputs.registry-paths }}"
